modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="ysm_mapping_api"
version="${version}"
displayName="YSM Mapping API"
description='''Runtime structural mappings for Yes Steve Model consumers.'''

[[dependencies.ysm_mapping_api]]
modId="forge"
mandatory=true
versionRange="[${forgeVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.ysm_mapping_api]]
modId="minecraft"
mandatory=true
versionRange="[${minecraftVersion}]"
ordering="NONE"
side="BOTH"

[[dependencies.ysm_mapping_api]]
modId="yes_steve_model"
mandatory=true
versionRange="[2.6.0,)"
ordering="AFTER"
side="BOTH"
